# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoursquareGroupProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoursquareGroupProject
 pod 'Mapbox-iOS-SDK', '~> 5.5'
 pod 'MapboxNavigation', '~> 0.38.3'
 pod 'MapboxGeocoder.swift', '~> 0.12'

  target 'FoursquareGroupProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
